# -*- coding: utf-8 -*-
"""Gross_pay.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19_bgFsUkuMQHSHrObe5O4TtGqCQGdr7p
"""

#Write a program to promt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5
#times the hourly rate for all hours worked above 40 hours.
hrs=input("Enter hours: ")
rateperhrs=input("Enter the rate per hour" )
if int(hrs) >40:
  print(float(rateperhrs) * 40 + (int(hrs)-40)*float(rateperhrs)*1.5)
  
else:
  print (int(hrs) * float(rateperhrs))